#!/usr/bin/env python2.7

import sys
import numpy

sys.path.append("/Users/john/src/jbr.py")
sys.path.append( "/home/john/src/jbr.py")

import fitsy

file = sys.argv[1]

fits = fitsy.open(file)

print "file	", file
print ""

print "crval1	", fits[0].CRVAL1
print "crpix1	", fits[0].CRPIX1
print "cdelt1	", fits[0].CDELT1
print ""

print "\t".join(["id", "target", "ra", "dec", "type", "fiber", "x", "y"])
print "\t".join(["--", "------", "--", "---", "----", "-----", "-", "-"])

for i in range(1, 301) :
    print i, "\t", "\t".join(fits[0]["APID" + str(i)].split())

nx = fits[0].NAXIS1

fits[0].data[0] = fits[0].data[0].clip(min=0);

for row in fits[0].data[0] :
    row[0:nx] /= row.sum();


print "\f\n"
for row in fits[0].data[0] :
    for x in row :
	print "%.10f" % x,

    print ""

